### ISSUE TITLE
Directory Listing

### ISSUE THREAD

**Issue by diegosanchezstrange** [soykilian/webserv#25]
Directory listing is a feature provided by many web servers that allows users to view the files and directories in the server's directory structure when they navigate to a directory that doesn't have an index file (like index.html or index.php).

It's like a file explorer for your web server. It can be useful for file sharing, but it's usually not desirable for public-facing websites as it can expose internal files and structure to potential attackers.

If you're creating a web server in C++, implementing this feature would involve checking whether directory listing is enabled when a request for a directory comes in. If it is enabled, and there's no index file in the directory, you would send a response containing a list of files and directories in that directory. If it's not enabled, you would send a 403 Forbidden or 404 Not Found response instead.

Here is a simple outline of how you might go about implementing this feature:

Configuration: Allow the server's operator to turn directory listing on or off. You could read this setting from a configuration file or command-line argument when the server starts. This value would be stored in a boolean variable, let's call it allowDirectoryListing.

Request handling: When a GET request comes in, check if the requested path points to a directory. You can do this using the stat or opendir functions in the C++ standard library. If the path is not a directory, handle it as you would normally.

Directory handling: If the requested path is a directory, check for an index file (like index.html or index.php). If an index file exists, serve that file. If not, check the value of allowDirectoryListing.

Directory listing: If allowDirectoryListing is true, create a HTML document that contains a list of links to the files and directories in the requested directory. You can get this list using the readdir function. This HTML document is the response to the GET request. If allowDirectoryListing is false, respond with a 403 Forbidden or 404 Not Found status code instead.

Remember that directory listing can expose sensitive data, so make sure it's only turned on when it's safe to do so. You might also want to add a way to exclude certain directories from directory listing, even when it's globally enabled.

https://chat.openai.com/share/9e60d3c3-0130-4897-be30-48eb0bd0136d

**Comment by soykilian** [comment]
yap
